/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fixed_usb_UsbRequest */

#ifndef _Included_com_fixed_usb_UsbRequest
#define _Included_com_fixed_usb_UsbRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fixed_usb_UsbRequest
 * Method:    native_init
 * Signature: (Lcom/fixed/usb/UsbDeviceConnection;IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fixed_usb_UsbRequest_native_1init
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     com_fixed_usb_UsbRequest
 * Method:    native_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fixed_usb_UsbRequest_native_1close
  (JNIEnv *, jobject);

/*
 * Class:     com_fixed_usb_UsbRequest
 * Method:    native_queue_array
 * Signature: ([BIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fixed_usb_UsbRequest_native_1queue_1array
  (JNIEnv *, jobject, jbyteArray, jint, jboolean);

/*
 * Class:     com_fixed_usb_UsbRequest
 * Method:    native_dequeue_array
 * Signature: ([BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_fixed_usb_UsbRequest_native_1dequeue_1array
  (JNIEnv *, jobject, jbyteArray, jint, jboolean);

/*
 * Class:     com_fixed_usb_UsbRequest
 * Method:    native_queue_direct
 * Signature: (Ljava/nio/ByteBuffer;IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fixed_usb_UsbRequest_native_1queue_1direct
  (JNIEnv *, jobject, jobject, jint, jboolean);

/*
 * Class:     com_fixed_usb_UsbRequest
 * Method:    native_dequeue_direct
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fixed_usb_UsbRequest_native_1dequeue_1direct
  (JNIEnv *, jobject);

/*
 * Class:     com_fixed_usb_UsbRequest
 * Method:    native_cancel
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fixed_usb_UsbRequest_native_1cancel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
